version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/zips:/app/zips
    environment:
      - UPLOAD_FOLDER=./uploads
      - ZIP_FOLDER=./zips
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  celery_worker:
    build:
      context: ./backend
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend/zips:/app/zips
      - ./backend/zips:/app/uploads


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
